columns = ['Carimbo de data/hora', 'Endereço de e-mail', 'NÚMERO DO RGM', 'Idade ',
           'SEXO', 'CURSO', 'SEMESTRE', 'TRABALHA ATUALMENTE?', 'TURMA:',
           '1)Eu posso identificar minhas necessidades, desejos, interesses e objetivos.',
           '2) Eu posso descrever minhas necessidades, desejos, interesses e objetivos.',
           '3) Posso identificar coisas em que sou bom e coisas em que não sou bom.',
           '4) Eu posso julgar meus pontos fortes e fracos e os dos outros em relação às oportunidades de criação de valor.',
           '5) Eu acredito na minha capacidade de fazer o que me perguntam com sucesso. ',
           ' 5) Eu acredito na minha capacidade de fazer o que me perguntam com sucesso. 6)Eu acredito na minha capacidade de alcançar o que pretendo.',
           '7) Eu posso mostrar respeito pelos outros, seus antecedentes e situações.',
           '8) Estou aberto ao valor que outros podem trazer para atividades criadoras de valor. ',
           '9) Eu posso mostrar empatia para com os outros.',
           '10) Posso reconhecer o papel das minhas emoções, atitudes e comportamentos na formação das atitudes e comportamentos das outras pessoas e vice-versa. ',
           '11) Eu posso mostrar empatia para com os outros. ',
           '12) Posso discutir os benefícios de ouvir as ideias de outras pessoas para alcançar meus objetivos (ou de minha equipe). ',
           '13) Estou aberto a trabalhar sozinho e com os outros, desempenhando papéis diferentes e assumindo alguma responsabilidade. ',
           '14) Estou disposto a mudar minha maneira de trabalhar em grupo.',
           '15) Estou aberto a envolver outras pessoas em minhas atividades criadoras de valor.',
           '16) Eu posso contribuir para atividades simples de criação de valor. ',
           '17) Eu posso contribuir para a tomada de decisões em grupo de forma construtiva. ',
           '1) Eu sou capaz de atingir a maior parte dos objetivos que defino para mim.',
           '2. Eu sou capaz de superar muitos desafios.',
           '3. Costumo ser persistente na busca de meus objetivos.',
           '4. Eu acredito que eu posso ter sucesso em quase qualquer coisa que eu resolva fazer.',
           '5. Eu posso fazer a maioria das coisas melhor do que as pessoas em geral.',
           '6. Mesmo quando as coisas estão difíceis, eu posso desempenhá-las muito bem.',
           '7. Quando faço planos, sei que posso fazer que eles deem certo.',
           '8. Se algo parece muito complicado eu nem tento fazer.',
           '9. Se eu não consigo fazer algo pela primeira vez, eu continuo tentando até conseguir.',
           '10. Eu sou uma pessoa autoconfiante.',
           '11. Quando eu defino objetivos importantes para mim eu raramente os atinjo.',
           '12. Quando traço um objetivo logo começo a colocá-lo em prática.',
           '13. Quando problemas inesperados acontecem, eu não lido bem com eles.',
           '14. Eu costumo persistir em meus planos.',
           '15. Sou confiante de que posso lidar bem com situações inesperadas.',
           '16. Eu desisto das coisas antes de completá-las.',
           '17. Quando enfrento problemas, geralmente posso encontrar várias soluções.',
           '18. Dificilmente eu vou me dar bem na vida.',
           '19. Quando eu falho, eu tenho vontade de tentar mais.',
           '20. Eu me sinto inseguro com relação a minha capacidade de fazer as coisas.']
